name: AROS build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-aros-tiny:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/src:/opt/code \
          -w /opt/code \
          -e BUILD=tiny \
          rolfkopman/arosi386v0env make -f Make_ami.mak
